# Generated by Django 3.2.3 on 2021-05-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
